
services:
  postgres:
    image: postgres:17.5-alpine3.22
    container_name: ev-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: RqsW^zOW3ogC*LlS
      POSTGRES_DB: eventstore
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:5.3.0-standalone
    container_name: ev-adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DEFAULT_USERNAME: admin
      ADMINER_DEFAULT_PASSWORD: RqsW^zOW3ogC*LlS
      ADMINER_DEFAULT_DATABASE: eventstore
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8080:8080

  nats:
    image: nats:2.10.9-alpine
    container_name: ev-nats
    restart: always
    ports:
      - "4222:4222"   # client connection
      - "8222:8222"   # monitoring
    command: ["-js", "-m", "8222"]  # enable JetStream and monitoring
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8222/"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  pg_data:
